jda:
  token: {DISCORD_TOKEN:}
  guild-id: {GUILD_ID:}

logging:
  level:
    ru.dense: DEBUG
    com.springframework: INFO

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/aston_bank_app}
    username: ${DB_USR:postgres}
    password: ${DB_PSWD:123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update